WebCommercial/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebCommercial.Models.Metier;
using WebCommercial.Models.MesExceptions;

namespace WebApplication1.Controllers
{
	public class ArticleController : Controller
	{
		// GET: Article
		public ActionResult Index()
		{
			IEnumerable<Article> articles = null;

			try
			{
				articles = Article.getArticles();
			}
			catch (MonException e)
			{
				ModelState.AddModelError("Erreur", "Erreur lors de la récupération des articles : " + e.Message);
				ViewBag.Message = "Liste des articles";
				return View("Error");
			}

			ViewBag.Title = "Liste des articles";
			return View(articles);
		}

		[Authorize]
		// GET: Commande/Edit/5
		public ActionResult Modifier(int id)
		{
			try
			{
				Article unAr = Article.getArticle(id);
				ViewBag.Title = "Modifier";
				return View(unAr);
			}
			catch (MonException e)
			{
				return HttpNotFound();
			}
		}

		[Authorize]
		[HttpPost]
		public ActionResult Modifier(Article unA)
		{
			if (!ModelState.IsValid)
			{
				// Si l'article modifié n'est pas valide, on affiche un message d'erreur à l'utilisateur
				return View(unA);
			}

			try
			{
				Article.updateArticle(unA);
				ViewBag.Title = "Modifier";

				return RedirectToAction("Index");
			}
			catch (MonException e)
			{
				return HttpNotFound();
			}
		}

		[Authorize]
		public ActionResult Ajouter()
		{
			try
			{
				ViewBag.Title = "Ajouter un article";
				return View();
			}
			catch (MonException e)
			{
				return HttpNotFound();
			}
		}

		[Authorize]
		[HttpPost]
		public ActionResult Ajouter(Article unA)
		{
			try
			{
				Article.insertArticle(unA);
				ViewBag.Title = "Ajouter un article";

				return RedirectToAction("Index");
			}
			catch (MonException e)
			{
				return View(unA);
			}
		}
	}
}

WebCommercial/Controllers/CLientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebCommercial.Models.Metier;
using WebCommercial.Models.MesExceptions;

namespace WebApplication1.Controllers
{
    public class ClientController : Controller
    {
        // GET: Client
        public ActionResult Index()
        {
            IEnumerable<Clientel> clients = null;

            try
            {
                clients = Clientel.getClients();
            }
            catch (MonException e)
            {
                ModelState.AddModelError("Erreur", "Erreur lors de la récupération des clients : " + e.Message);
                ViewBag.Message = "Liste des clients";
                return View("Error");
            }

            ViewBag.Title = "Liste des clients";
            return View(clients);
        }

        [Authorize]
        // GET: Commande/Edit/5
        public ActionResult Modifier(int id)
        {
            try
            {
                Clientel unCl = Clientel.getClient(id);
                ViewBag.Title = "Modifier";
                return View(unCl);
            }
            catch (MonException e)
            {
                return HttpNotFound();
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Modifier(Clientel unC)
        {
            if (!ModelState.IsValid)
            {
                // Si le client modifié n'est pas valide, on affiche un message d'erreur à l'utilisateur
                return View(unC);
            }
                
            try
            {
                // utilisation possible de Request
               //  String s= Request["Societe"];

                Clientel.updateClient(unC);
                ViewBag.Title = "Modifier";

                return RedirectToAction("Index");
            }
            catch (MonException e)
            {
                return HttpNotFound();
            }
        }

        [Authorize]
        public ActionResult Ajouter()
        {
            try
            {
                ViewBag.Title = "Ajouter un client";
                return View();
            }
            catch (MonException e)
            {
                return HttpNotFound();
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Ajouter(Clientel unC)
        {
            /*List<String> mesNumeros;
            int num;

            // Test pour savoir quel ID on peut donner au client créé
            try
            {
                mesNumeros = Clientel.LectureNoClient();
                if(int.TryParse(mesNumeros.Last(), out num))
                {
                    num++;
                }
            }*/

            try
            {
                // utilisation possible de Request
                //  String s= Request["Societe"];

                Clientel.insertClient(unC);
                ViewBag.Title = "Ajouter un client";

                return RedirectToAction("Index");
            }
            catch (MonException e)
            {
                return View(unC);
            }
        }
    }
}

WebCommercial/Controllers/CommandeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebCommercial.Models.MesExceptions;
using WebCommercial.Models.Metier;

namespace WebCommercial.Controllers
{
    public class CommandeController : Controller
    {
        // GET: Commande
        public ActionResult Index()
        {
            IEnumerable<Commande> commandes = null;

            try
            {
                commandes = Commande.getCommandes();
            }
            catch (MonException e)
            {
                ModelState.AddModelError("Erreur", "Erreur lors de la récupération des commandes : " + e.Message);
                ViewBag.Message = "Liste des commandes";
                return View("Error");
            }

            ViewBag.Title = "Liste des commandes";
            return View(commandes);
        }

        [Authorize]
        public ActionResult Modifier(int id)
        {
            try
            {
                Commande uneCom = Commande.getCommande(id);
                ViewBag.Title = "Modifier commande N°" + id;

                List<SelectListItem> items = new List<SelectListItem>();
                foreach (String no in Vendeur.LectureNoVendeurs())
                {
                    if(int.Parse(no) == uneCom.NoVendeur)
                    {
                        items.Add(new SelectListItem { Text = "Vendeur N°"+no, Value = no , Selected = true });
                    } else
                    {
                        items.Add(new SelectListItem { Text = "Vendeur N°"+no, Value = no });
                    }
                }
                ViewBag.NoVendeurs = items;

                items = new List<SelectListItem>();
                foreach (String no in Clientel.LectureNoClients())
                {
                    if (int.Parse(no) == uneCom.NoClient)
                    {
                        items.Add(new SelectListItem { Text = "Client N°" + no, Value = no, Selected = true });
                    }
                    else
                    {
                        items.Add(new SelectListItem { Text = "Client N°" + no, Value = no });
                    }
                }
                ViewBag.NoClients = items;

                items = new List<SelectListItem>();
                foreach (Article art in Article.getArticles())
                {
                    items.Add(new SelectListItem { Text = art.NoArticle + "/;/" + art.Libelle + "/;/" + art.Prix, Value = art.NoArticle.ToString() });
                }
                ViewBag.Articles = items;

                return View(uneCom);
            }
            catch (MonException e)
            {
                return HttpNotFound();
            }
        }
        
        [Authorize]
        [HttpPost]
        public ActionResult AjouterArticle()  
        {
            try
            {
                int id = int.Parse(Request["NoCommandeArt"]);
                int noart = int.Parse(Request["NoArt"]);
                int quantite = int.Parse(Request["QuantiteArt"]);
                string livree = Request["Livree"];
                Article art = new Article();
                art.NoArticle = noart;
                Commande.addArticleInCommande(id, new ArticleCommande(art, quantite, livree));

                return RedirectToAction("Modifier", new { id= id });
            }
            catch (MonException e)
            {
                return View("Error");
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult ModifierArticle()
        {
            try
            {
                int id = int.Parse(Request["NoCommandeArt"]);
                int noart = int.Parse(Request["NoArt"]);
                int quantite = int.Parse(Request["QuantiteArt"]);
                string livree = Request["Livree"];
                Article art = new Article();
                art.NoArticle = noart;
                Commande.updateArticleInCommande(id, new ArticleCommande(art, quantite, livree));

                return RedirectToAction("Modifier", new { id = id });
            }
            catch (MonException e)
            {
                return View("Error");

            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult SupprimerArticle()
        {
            try
            {
                int id = int.Parse(Request["NoCommandeArt"]);
                int noart = int.Parse(Request["NoArt"]);
                Commande.deleteArticleInCommande(id, noart);

                return RedirectToAction("Modifier", new { id = id });
            }
            catch (MonException e)
            {
                return View("Error");

            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Modifier(Commande uneCom)
        {
            /*if (!ModelState.IsValid)
            {
                // Si le client modifié n'est pas valide, on affiche un message d'erreur à l'utilisateur
                return View(uneCom);
            }*/

            try
            {
                Commande.updateCommande(uneCom);

                return RedirectToAction("Modifier", uneCom.NoCommande);
            }
            catch (MonException e)
            {
                return HttpNotFound();
            }
        }

        [Authorize]
        public ActionResult Ajouter()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (String no in Vendeur.LectureNoVendeurs())
            {
                items.Add(new SelectListItem { Text = "Vendeur N°" + no, Value = no });
            }
            ViewBag.NoVendeurs = items;

            items = new List<SelectListItem>();
            foreach (String no in Clientel.LectureNoClients())
            {
                items.Add(new SelectListItem { Text = "Client N°" + no, Value = no });
            }
            ViewBag.NoClients = items;

            items = new List<SelectListItem>();
            foreach (Article art in Article.getArticles())
            {
                items.Add(new SelectListItem { Text = art.NoArticle + "/;/" + art.Libelle + "/;/" + art.Prix, Value = art.NoArticle.ToString() });
            }
            ViewBag.Articles = items;

            try
            {
                ViewBag.Title = "Ajouter une commande";

                return View();
            }
            catch (MonException e)
            {
                return HttpNotFound();
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Ajouter(Commande uneCom)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (String no in Vendeur.LectureNoVendeurs())
            {
                if (int.Parse(no) == uneCom.NoVendeur)
                {
                    items.Add(new SelectListItem { Text = "Vendeur N°" + no, Value = no, Selected = true });
                }
                else
                {
                    items.Add(new SelectListItem { Text = "Vendeur N°" + no, Value = no });
                }
            }
            ViewBag.NoVendeurs = items;

            items = new List<SelectListItem>();
            foreach (String no in Clientel.LectureNoClients())
            {
                if (int.Parse(no) == uneCom.NoClient)
                {
                    items.Add(new SelectListItem { Text = "Client N°" + no, Value = no, Selected = true });
                }
                else
                {
                    items.Add(new SelectListItem { Text = "Client N°" + no, Value = no });
                }
            }
            ViewBag.NoClients = items;

            items = new List<SelectListItem>();
            foreach (Article art in Article.getArticles())
            {
                items.Add(new SelectListItem { Text = art.NoArticle + "/;/" + art.Libelle + "/;/" + art.Prix, Value = art.NoArticle.ToString() });
            }
            ViewBag.Articles = items;

            try
            {
                int id = Commande.insertCommande(uneCom);

                return RedirectToAction("Modifier", new { id = id });
            }
            catch (MonException e)
            {
                ViewBag.Title = "Ajouter une commande";
                return View();
            }
        }
    }
}

WebCommercial/Views/Shared/ConfirmationModal.cshtml
<div class="modal fade" id="confirmationMessageModal" tabindex="-1" role="dialog" aria-labelledby="confirmationMessageModal" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title font-weight-bold" id="confirmationMessageTitre">Titre</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="container-fluid">
                    <p id="confirmationMessageText"></p>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" id="confirmationMessageValider">Enregistrer</button>
                <button type="button" class="btn btn-default btn-secondary" data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>

WebCommercial/Views/Shared/Menu.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Polytech Commercial", "", "", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Fichier<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li class="dropdown-header">Application</li>
            <li class="dropdown-header">----------</li>
            <li role="separator" class="divider"></li>
            <li>@Html.ActionLink("Se déconnecter", "Deconnexion", "Vendeur")</li>
        </ul>
    </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Interroger<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">Fiches</li>
                        <li role="separator" class="divider"></li>
                        <li>@Html.ActionLink("Liste des Clients", "Index", "Client")</li>
                        <li>@Html.ActionLink("Liste des articles", "Index", "Article")</li>
                        <li>@Html.ActionLink("Liste des Vendeurs", "Index", "Vendeur")</li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">Commandes</li>
                        <li role="separator" class="divider"></li>
                        <li>@Html.ActionLink("Liste des Commandes", "Index", "Commande")</li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gérer<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">Gestion</li>
                        <li role="separator" class="divider"></li>
                        <li>@Html.ActionLink("Ajouter Client", "Ajouter", "Client")</li>
                        <li>@Html.ActionLink("Ajouter Article", "Ajouter", "Article")</li>
                        <li>@Html.ActionLink("Modifier Article", "Index", "Article")</li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">Produits</li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Augmenter Prix</a></li>
                    </ul>
                </li>
                <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                @if (Context.User.Identity.IsAuthenticated)
                {
                    <li>@Html.ActionLink("Ma Fiche", "FicheVendeur", "Vendeur", new { id = Context.User.Identity.Name }, null)</li>
                    <li>@Html.ActionLink("Se Déconnecter", "Deconnexion", "Vendeur")</li>
                }
                else
                {
                    <li>@Html.ActionLink("Se Connecter", "Connexion", "Vendeur")</li>
                }
            </ul>
        </div>
    </div>
</div>

WebCommercial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom de l'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebCommercial/Views/Shared/_LayoutCommercial.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Web Commercial ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("Menu")
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p> @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/scriptModal.js")
    @RenderSection("scripts", required: false)
</body>
</html>